version: '3.7'
services:
  logstash:
    image: logstash:7.9.3
    container_name: logstash
    hostname: logstash
    networks:
      - elkw
    volumes:
      - ./logstash/configs/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/configs/pipeline:/usr/share/logstash/pipeline

networks:
  elkw:
