version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es
    hostname: elastic
    environment:
      - discovery.type=single-node
#curl https://localhost:9200 -u elastic:TuX9JcUcagY84YhubAvP -k
