version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es
    hostname: elastic
    environment:
      - discovery.type=single-node
#curl https://localhost:9200 -u elastic:TuX9JcUcagY84YhubAvP -k

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    hostname: kibana
    
