version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es
    hostname: elastic
    environment:
      - discovery.type=single-node
    networks:
      - elkw

networks:
  elkw: