version: '3.7'
services:
  kibana:
    image: kibana:7.9.3
    container_name: kibana
    hostname: kibana
    networks:
      - elkw
    volumes:
      - ./kibana/configs/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
networks:
  elkw:
